DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

PLATINUM_WORKSPACE=${DIR}
PLATINUM_PREFIX=${DIR}/LOCAL
PYTHONUSERBASE=${PLATINUM_PREFIX}

PATH=${PLATINUM_PREFIX}/bin:${PATH}
LD_LIBRARY_PATH=${PLATINUM_PREFIX}/lib64:${LD_LIBRARY_PATH}

export PATH
export LD_LIBRARY_PATH
export LOCAL
export PYTHONUSERBASE
export PLATINUM_WORKSPACE
export PLATINUM_PREFIX
