module load python/3
module load jdk/1.8.0_71
module load meson
module load gcc/8.3.0
module load nim
module load cram
module load boost
module load zlib
module load htslib
module load samtools
module load gtest
module load git
module load snakemake/5.4.3-ve
